extern alias MountAndBlade;
using System;
using System.Collections.Generic;
using System.Linq;
using MountAndBlade.System.Numerics;
using System.Text;
using System.Threading.Tasks;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1;

namespace InGameUIDesigner.EditorOperations
{
    public class AddWidgetOperation : UIEditorOperation
    {
        public AddWidgetOperation(Widget addedWidget)
        {
            _addedWidget = addedWidget;
        }

        private Widget _addedWidget;
        public override UIEditorOperationType OperationType => UIEditorOperationType.AddedWidget;
        public override void Undo()
        {
            UIEditorVM.Instance.RemoveWidget(_addedWidget, false);
        }

        public override UIEditorOperation GetRedoOp()
        {
            return new RemoveWidgetOperation(_addedWidget, _addedWidget.ParentWidget);
        }
    }
}
